Batanoff update readme
ValentinnDimitroff/ra-auth-ui pull request #12
Opened 2024-03-07 10:44 UTC by batanoffs

updated readme and yarn.lock (versions)

2024-03-09 13:55 UTC, ValentinnDimitroff requested changes
Please, also modify the `start-demo` script in the `package.json` to call `yarn dev` instead of `yarn start`

2024-03-09 13:55 UTC, ValentinnDimitroff commented on README.md
> +yarn dev
Actaully we want to still run `yarn start-demo` but just add a note to install the node modules the first time before running the project

2024-03-09 13:55 UTC, ValentinnDimitroff commented on examples/demo/yarn.lock
Let's reset this file, we don't want to upgrade dependencies here

2024-03-29 11:44 UTC, batanoffs commented on examples/demo/yarn.lock
Added new commit where i revert the changes

2024-04-02 07:59 UTC, ValentinnDimitroff approved these changes

2024-04-15 07:50 UTC, ValentinnDimitroff commented
Are we gonna merge this one @batanoffs  :)

2024-04-15 15:10 UTC, merged