Refactor Profile Page props to work in three possible modes
ValentinnDimitroff/ra-auth-ui pull request #24
Opened 2024-09-23 15:31 UTC by batanoffs

## Title: [For Review] Refactor profile page props to work in three possible modes.
### Summary
Changes made according to this [task](https://github.com/ValentinnDimitroff/ra-auth-ui/issues/16). Also added `defaultPasswordRules` (not fully implemented yet, future update in next pull request).
- `profilePage` now supports three possible modes: `default`, 'boolean', and `component`. 
- Route has been added for the custom profile component
- Demo added in examples 

### Detailed Description

**IMPORTANT** Please consider the import for `AuthAdmin` needs to be changed for production. Comment has been added.

The following changes have been made:

- export `profilePage`
- added `profilePage` item into `userMenu` dropdown, complemented with conditionals
- update types and defaults for `authOptions` with new `profilePage` and `passwordRules` (password rules not implemented yet)
- added default values for `defaultPasswordRules`
- update `AuthOptionsContextType` to support `profilePage` options
- added route for profilePage 
```jsx
    <Route
          path={PROFILE_ROUTE}
          element={
              authOptions.profilePage === true ? (
                  <ProfilePage />
              ) : authOptions.profilePage === false ? null : (
                  authOptions.profilePage
              )
          }
      />
```
- update `defaultAuthOptions` to support `profilePage` props and fix children's type error for typescript
- add `TestProfile.tsx` in examples to test custom components.

### Checklist
I have performed a self-review of my code, double checked and tested with an example demo.
My changes generate no new warnings.
Commented on my code for more clarity.

2024-11-05 10:05 UTC, ValentinnDimitroff requested changes
Overall looks pretty good - some minor comments to polish it and also one note: With each change/addition of new feature, we need to make sure the Readme is up to date so probably a good idea to add the following changes as a description there in the current PR.

2024-11-05 10:33 UTC, batanoffs commented on src/pages/profile/ProfileDetailsCard.tsx
> +    RequiteDigit?: boolean
I will check this

2024-11-12 13:34 UTC, batanoffs commented
Updated according to the requested changes. Please review the new changes. I have also resolved some conflicts for the readme file.

2024-11-12 20:49 UTC, ValentinnDimitroff commented on src/utils.ts
> +    requiredSymbols?: boolean
What's the difference between `requiredSymbols` and `requiredNonAlphanumeric` ?

2024-11-12 20:49 UTC, ValentinnDimitroff commented on src/AuthAdmin.tsx
> +                    {authOptions.profilePage !== false && <Route path={PROFILE_ROUTE} element={ProfileComponent} />}
If someone passes a `null` value for the `profilePage` prop - I believe this code will produce a route which leads to a null component

2024-11-12 20:49 UTC, ValentinnDimitroff commented on src/AuthAdmin.tsx
> +                    {authOptions.profilePage !== false && <Route path={PROFILE_ROUTE} element={ProfileComponent} />}
```suggestion
                    {authOptions.profilePage && <Route path={PROFILE_ROUTE} element={ProfileComponent} />}
```

2024-11-13 10:27 UTC, batanoffs commented on src/utils.ts
> +    requiredSymbols?: boolean
My idea was to group them like punctuation characters ! @ # & ( ) – [ { } ] : ; ', ? / * and symbol characters \` ~ $ ^ + = < > “. But I see the confusion here. I forgot to update the naming properly and so on. On second review, it's probably better to use only one rule, for example `requiredSymbols`. it's easier to understand.

2024-11-13 10:32 UTC, batanoffs commented on src/AuthAdmin.tsx
> +                    {authOptions.profilePage !== false && <Route path={PROFILE_ROUTE} element={ProfileComponent} />}
Yes, updated

2024-11-19 17:21 UTC, ValentinnDimitroff reviewed
Only readme related comments

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +| `authLayout`  | object            | undefined | *If set to '{userMenu: true}' provides default UserMenu. If set to object pass on the props to Layout.* |
The prop is called `authOptions`.  It should point to the details of how the prop works, we can't explain all the features in the box here.

```suggestion
| `authOptions`  | object            | undefined | *If unset provides default Profile Page, integrated User Menu and password rules out of the box. All supported fields explained [below](#functionality-of-authlayout)* |
```

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +## Functionality of authLayout
```suggestion
## Functionality of authOptions
```

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +    | profilePage   | boolean | true        | *By default profile page is enabled and a basic profile component is set.*                                                         |
```suggestion
    | profilePage   | boolean | Component | true        | *By default profile page is enabled and a basic profile component is set. You can opt out by setting it to `false` or pass your own component which will be rendered at the `/profile` route*                                                         |
```

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +    | Props         | Type    | Defaults    | Behavior                                                                                                                           |
As a rule of thumb we can copy the react-admin style of describing props: https://marmelab.com/react-admin/Admin.html#props

```suggestion
    | Props         | Type    | Defaults    | Description                                                                                                                           |
```

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +    | userMenuItems | array   | empty array | *Not specified.*                                                                                                                   |
```suggestion
    | userMenuItems | array   | empty array | *Populates the user menu with items depending on the `authOptions` configuration*                                                                                                                   |
```

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +- ### profilePage
This is duplicated and outdated

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +      -   sideBar
This is outdated

2024-11-19 17:21 UTC, ValentinnDimitroff commented on README.md
> +    | passwordRules | object  | all enabled | *By default all rules are enabled. A digit, lowercase, non-alphanumeric,uppercase,min-length is `8` and min one symbol is needed.* |
`loginRedirectPath` is missing in the table

2024-11-19 17:25 UTC, ValentinnDimitroff commented on src/utils.ts
> +    requiredMinSymbols?: number
I actually liked the `requireNonAlphanumeric` prop better. Also having it as a bool property is enough e.g. having any symbol or none

2024-11-19 17:25 UTC, ValentinnDimitroff commented on src/AuthAdmin.tsx
> +    passwordRules: defaultPasswordRules || null, // TODO - not yet implemented
There is no need of `||` - `defaultPasswordRules` is a constant expression, it's never going to be null

2024-11-19 17:25 UTC, ValentinnDimitroff commented on prettier.config.js
> +    printWidth: 150,
Why?

2024-11-22 10:30 UTC, batanoffs commented on README.md
> +| `authLayout`  | object            | undefined | *If set to '{userMenu: true}' provides default UserMenu. If set to object pass on the props to Layout.* |
Fair, will update accordingly.

2024-11-22 10:40 UTC, batanoffs commented on src/utils.ts
> +    requiredMinSymbols?: number
okey, will update it

2024-11-22 10:44 UTC, batanoffs commented on prettier.config.js
> +    printWidth: 150,
Helps me read better, but I can work with 100 if you prefer. It's not a problem

2024-11-22 10:45 UTC, batanoffs commented on README.md
> +      -   sideBar
removed

2024-12-04 21:37 UTC, ValentinnDimitroff approved these changes

2024-12-14 15:40 UTC, merged